const form=document.querySelector('#horoscope-form'),sign=document.querySelector('#sign'),status=document.querySelector('#reading-status'),submit=document.querySelector('#submit-reading'),cancel=document.querySelector('#cancel-reading'),reading=document.querySelector('#reading');
for(const name of ['Rat','Ox','Tiger','Rabbit','Dragon','Snake','Horse','Goat','Monkey','Rooster','Dog','Pig']){const o=document.createElement('option');o.value=name.toUpperCase();o.textContent=name;sign.append(o)}
let controller=null,requestId=0;const cache=new Map();
function clearErrors(){document.querySelector('#form-error').textContent='';for(const id of ['sign']){document.querySelector('#'+id).removeAttribute('aria-invalid');document.querySelector('#'+id+'-error').textContent=''}}
function validate(){clearErrors();let first=null;for(const [field,message] of [[sign,'Choose your Chinese zodiac animal.']]){if(!field.checkValidity()){field.setAttribute('aria-invalid','true');document.querySelector('#'+field.id+'-error').textContent=message;first??=field}}if(first){document.querySelector('#form-error').textContent='Please correct the highlighted fields.';first.focus();return false}return true}
function busy(value){submit.setAttribute('aria-disabled',String(value));submit.textContent=value?'Loading reading…':'Explore zodiac sign';cancel.hidden=!value;form.setAttribute('aria-busy',String(value))}
function display(data,cached){reading.hidden=false;document.querySelector('#reading-title').textContent=data.sign+' zodiac profile';document.querySelector('#reading-date').textContent='General zodiac description · Not a daily prediction';const target=document.querySelector('#predictions');target.replaceChildren();for(const [name,value] of Object.entries(data.prediction)){const card=document.createElement('article');card.className='entry card card-body h-100 p-4';const h=document.createElement('h3');h.textContent=name.charAt(0).toUpperCase()+name.slice(1);card.append(h);if(Array.isArray(value)){const ul=document.createElement('ul');for(const text of value){const li=document.createElement('li');li.textContent=text;ul.append(li)}card.append(ul)}else{const p=document.createElement('p');p.textContent=value;card.append(p)}const col=document.createElement('div');col.className='col';col.append(card);target.append(col)}status.textContent=cached?'Reading loaded from this session’s recent results.':'Reading received from AstroWay.';document.querySelector('#reading-title').focus()}
form.addEventListener('submit',async event=>{event.preventDefault();if(controller||!validate())return;reading.hidden=true;const input={sign:sign.value};const key=JSON.stringify(input);const old=cache.get(key);if(old&&Date.now()-old.time<60000){display(old.data,true);return}const id=++requestId;controller=new AbortController();const signal=controller.signal;let timedOut=false;const timer=setTimeout(()=>{timedOut=true;controller?.abort()},20000);busy(true);status.textContent='Loading your zodiac description…';try{const r=await fetch('https://api.astroway.info/v1/public/chinese/zodiac/texts?lang=en',{signal});if(!r.ok)throw Error(r.status===429?'Too many requests. Please wait a minute and try again.':'The zodiac service is unavailable. Please try again.');let payload;try{payload=await r.json()}catch{throw Error('The service returned an unreadable response. Please try again.')}const animal=payload.data?.animals?.[input.sign.toLowerCase()];if(!payload.ok||!animal||!['character','strengths','caution'].every(k=>typeof animal[k]==='string'))throw Error('No valid zodiac description was returned. Please try again.');const data={sign:animal.name||input.sign,prediction:{character:animal.character,strengths:animal.strengths,caution:animal.caution}};if(id!==requestId)return;cache.set(key,{data,time:Date.now()});display(data,false)}catch(error){if(id!==requestId)return;status.textContent=signal.aborted?(timedOut?'The request timed out. Please try again.':'Request cancelled.'):(error instanceof TypeError?'Unable to connect. Check your internet connection and try again.':error.message)}finally{clearTimeout(timer);if(id===requestId){controller=null;busy(false)}}});
cancel.addEventListener('click',()=>{controller?.abort();submit.focus()});
form.addEventListener('reset',()=>{requestId++;controller?.abort();controller=null;busy(false);clearErrors();reading.hidden=true;status.textContent='Form reset.';setTimeout(()=>{sign.focus()},0)});
